// Country list shared by RA / IRP residency + citizenship questions.
// Cleaned from the Google Form export: OCR typos fixed (Iran/Italy/Iceland/
// Bumma → Burma, Moldov → Moldova, Cyrillic Kenya, etc.), "Islands" spelling
// normalized, hyphenation tightened. "Other" kept as the last option.

export const COUNTRIES = [
  'Afghanistan',
  'Åland Islands (Finland)',
  'Albania',
  'Algeria',
  'American Samoa (USA)',
  'Andorra',
  'Angola',
  'Anguilla (UK)',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba (Netherlands)',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belize',
  'Benin',
  'Bermuda (UK)',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'British Virgin Islands (UK)',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burma (Myanmar)',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Caribbean Netherlands (Netherlands)',
  'Cayman Islands (UK)',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island (Australia)',
  'Cocos (Keeling) Islands (Australia)',
  'Colombia',
  'Comoros',
  'Cook Islands (NZ)',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Curaçao (Netherlands)',
  'Cyprus',
  'Czech Republic',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands (UK)',
  'Faroe Islands (Denmark)',
  'Federated States of Micronesia',
  'Fiji',
  'Finland',
  'France',
  'French Guiana (France)',
  'French Polynesia (France)',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar (UK)',
  'Greece',
  'Greenland (Denmark)',
  'Grenada',
  'Guadeloupe (France)',
  'Guam (USA)',
  'Guatemala',
  'Guernsey (UK)',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hong Kong (China)',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle of Man (UK)',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jersey (UK)',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macau (China)',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique (France)',
  'Mauritania',
  'Mauritius',
  'Mayotte (France)',
  'Mexico',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat (UK)',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia (France)',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue (NZ)',
  'Norfolk Island (Australia)',
  'North Korea',
  'Northern Mariana Islands (USA)',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn Islands (UK)',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Republic of the Congo',
  'Réunion (France)',
  'Romania',
  'Russia',
  'Saint Barthélemy (France)',
  'Saint Helena, Ascension and Tristan da Cunha (UK)',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin (France)',
  'Saint Pierre and Miquelon (France)',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'São Tomé and Príncipe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten (Netherlands)',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen (Norway)',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau (NZ)',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands (UK)',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States of America',
  'U.S. Virgin Islands (USA)',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Wallis and Futuna (France)',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Other',
]
